use regex::Regex;
use std::collections::HashSet;

/// Outcome action for a page scan.
#[derive(Debug, Clone, serde::Serialize)]
#[serde(tag = "type", content = "message")]
pub enum SlopAction {
    None,
    SubtleBadge(String),
    WarnBanner(String),
}

/// Full report produced by the slop analysis pipeline.
#[derive(Debug, Clone, serde::Serialize)]
pub struct PageReport {
    pub url: String,
    pub blocked_scripts: Vec<String>,
    pub affiliate_count: u32,
    pub llm_marker_count: u32,
    pub slop_score: f64,
    pub action: SlopAction,
}

/// Compiled patterns for fast content analysis.
pub struct SlopShield {
    tracking_patterns: Vec<Regex>,
    affiliate_patterns: Vec<Regex>,
    llm_phrases: Vec<String>,
    blocked_domains: HashSet<String>,
}

impl SlopShield {
    pub fn new() -> Self {
        let tracking_patterns = vec![
            Regex::new(r#"src=["'][^"']*google-analytics\.com"#).unwrap(),
            Regex::new(r#"src=["'][^"']*googletagmanager\.com"#).unwrap(),
            Regex::new(r#"src=["'][^"']*doubleclick\.net"#).unwrap(),
            Regex::new(r#"src=["'][^"']*googlesyndication\.com"#).unwrap(),
            Regex::new(r#"src=["'][^"']*facebook\.net/en_US/fbevents"#).unwrap(),
            Regex::new(r#"src=["'][^"']*connect\.facebook\.net"#).unwrap(),
            Regex::new(r#"src=["'][^"']*hotjar\.com"#).unwrap(),
            Regex::new(r#"src=["'][^"']*clarity\.ms"#).unwrap(),
            Regex::new(r#"src=["'][^"']*segment\.io"#).unwrap(),
            Regex::new(r#"src=["'][^"']*mixpanel\.com"#).unwrap(),
            Regex::new(r#"src=["'][^"']*amplitude\.com"#).unwrap(),
            Regex::new(r#"src=["'][^"']*ads-twitter\.com"#).unwrap(),
            Regex::new(r#"src=["'][^"']*snap\.licdn\.com"#).unwrap(),
            Regex::new(r#"src=["'][^"']*bat\.bing\.com"#).unwrap(),
            Regex::new(r#"src=["'][^"']*tiktok\.com/i18n/pixel"#).unwrap(),
        ];

        let affiliate_patterns = vec![
            Regex::new(r"[?&]tag=[A-Za-z0-9_-]+-20").unwrap(),           // Amazon affiliate
            Regex::new(r"shareasale\.com").unwrap(),
            Regex::new(r"commission-junction\.com|cj\.com/redirect").unwrap(),
            Regex::new(r"impact\.com/[a-z]+/[a-z]+").unwrap(),
            Regex::new(r"bit\.ly/[A-Za-z0-9]+").unwrap(),
            Regex::new(r"amzn\.to/[A-Za-z0-9]+").unwrap(),
            Regex::new(r"geni\.us/[A-Za-z0-9]+").unwrap(),
            Regex::new(r"linksynergy\.com").unwrap(),
            Regex::new(r"awin1\.com").unwrap(),
            Regex::new(r"clickbank\.net").unwrap(),
            Regex::new(r"jdoqocy\.com|tkqlhce\.com|anrdoezrs\.net").unwrap(),
        ];

        let llm_phrases = vec![
            "as an ai language model",
            "it's important to note",
            "in today's rapidly evolving",
            "comprehensive guide",
            "let's dive deep",
            "game-changer",
            "revolutionizing",
            "delve into",
            "harness the power",
            "navigate the complexities",
        ]
        .into_iter()
        .map(String::from)
        .collect();

        let blocked_domains: HashSet<String> = vec![
            "contentfarm.example.com",
            "spammy-seo-site.com",
            "autogenerated-articles.net",
        ]
        .into_iter()
        .map(String::from)
        .collect();

        Self {
            tracking_patterns,
            affiliate_patterns,
            llm_phrases,
            blocked_domains,
        }
    }

    /// Run full analysis on a page's HTML.
    pub fn analyze_page(&self, html: &str, url: &str) -> PageReport {
        let blocked_scripts = self.find_blocked_scripts(html);
        let affiliate_count = self.count_affiliates(html);
        let llm_marker_count = self.count_llm_markers(html);
        let slop_score = self.compute_slop(&blocked_scripts, affiliate_count, llm_marker_count);

        let action = if slop_score >= 0.7 {
            SlopAction::WarnBanner(format!(
                "High slop score ({:.0}%): this page has heavy tracking, affiliate links, or AI-generated content.",
                slop_score * 100.0
            ))
        } else if slop_score >= 0.35 {
            SlopAction::SubtleBadge(format!("Slop: {:.0}%", slop_score * 100.0))
        } else {
            SlopAction::None
        };

        PageReport {
            url: url.to_string(),
            blocked_scripts,
            affiliate_count,
            llm_marker_count,
            slop_score,
            action,
        }
    }

    fn find_blocked_scripts(&self, html: &str) -> Vec<String> {
        let mut found = Vec::new();
        for pat in &self.tracking_patterns {
            for m in pat.find_iter(html) {
                found.push(m.as_str().to_string());
            }
        }
        found
    }

    fn count_affiliates(&self, html: &str) -> u32 {
        let mut count = 0u32;
        for pat in &self.affiliate_patterns {
            count += pat.find_iter(html).count() as u32;
        }
        count
    }

    fn count_llm_markers(&self, html: &str) -> u32 {
        let lower = html.to_lowercase();
        let mut count = 0u32;
        for phrase in &self.llm_phrases {
            count += lower.matches(phrase.as_str()).count() as u32;
        }
        count
    }

    fn compute_slop(
        &self,
        blocked_scripts: &[String],
        affiliate_count: u32,
        llm_marker_count: u32,
    ) -> f64 {
        // Each signal contributes a fraction: tracking 0-0.3, affiliates 0-0.3, LLM 0-0.4
        let tracking_score = (blocked_scripts.len() as f64 / 5.0).min(1.0) * 0.3;
        let affiliate_score = (affiliate_count as f64 / 5.0).min(1.0) * 0.3;
        let llm_score = (llm_marker_count as f64 / 3.0).min(1.0) * 0.4;
        (tracking_score + affiliate_score + llm_score).min(1.0)
    }

    /// Check if a domain is on the hardcoded block list.
    pub fn is_blocked_domain(&self, domain: &str) -> bool {
        let domain_lower = domain.to_lowercase();
        self.blocked_domains.contains(&domain_lower)
    }
}

/// Tauri command: analyse a page and return a slop report.
#[tauri::command]
pub fn get_slop_report(
    html: String,
    url: String,
    shield: tauri::State<'_, SlopShield>,
) -> PageReport {
    shield.analyze_page(&html, &url)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn shield() -> SlopShield {
        SlopShield::new()
    }

    #[test]
    fn test_clean_html_no_trackers() {
        let s = shield();
        let scripts = s.find_blocked_scripts("<html><body>Hello</body></html>");
        assert!(scripts.is_empty());
    }

    #[test]
    fn test_detects_ga_tracker() {
        let s = shield();
        let html = r#"<script src="https://www.google-analytics.com/analytics.js"></script>"#;
        let scripts = s.find_blocked_scripts(html);
        assert!(!scripts.is_empty());
    }

    #[test]
    fn test_affiliate_amazon_tag() {
        let s = shield();
        let html = r#"<a href="https://amazon.com/dp/B00?tag=mysite-20">buy</a>"#;
        assert!(s.count_affiliates(html) >= 1);
    }

    #[test]
    fn test_no_affiliates_zero() {
        let s = shield();
        assert_eq!(s.count_affiliates("<p>clean page</p>"), 0);
    }

    #[test]
    fn test_llm_marker_detection() {
        let s = shield();
        let html = "As an AI language model, let's dive deep into this comprehensive guide.";
        assert!(s.count_llm_markers(html) >= 2);
    }

    #[test]
    fn test_clean_text_no_markers() {
        let s = shield();
        assert_eq!(s.count_llm_markers("Rust is a systems programming language."), 0);
    }

    #[test]
    fn test_slop_score_clean_zero() {
        let s = shield();
        let score = s.compute_slop(&[], 0, 0);
        assert!((score - 0.0).abs() < f64::EPSILON);
    }

    #[test]
    fn test_slop_score_high() {
        let s = shield();
        let scripts = vec!["a".into(), "b".into(), "c".into(), "d".into(), "e".into()];
        let score = s.compute_slop(&scripts, 5, 3);
        assert!(score >= 0.7);
    }

    #[test]
    fn test_analyze_clean_page_none_action() {
        let s = shield();
        let report = s.analyze_page("<html><body>Hello world</body></html>", "https://clean.com");
        assert!(matches!(report.action, SlopAction::None));
    }

    #[test]
    fn test_analyze_slop_page_warn() {
        let s = shield();
        let html = r#"
            <script src="https://www.google-analytics.com/a.js"></script>
            <script src="https://www.googletagmanager.com/b.js"></script>
            <script src="https://www.doubleclick.net/c.js"></script>
            <script src="https://www.googlesyndication.com/d.js"></script>
            <script src="https://connect.facebook.net/e.js"></script>
            <a href="https://amzn.to/abc">link</a>
            <a href="https://amzn.to/def">link</a>
            <a href="https://amzn.to/ghi">link</a>
            <a href="https://shareasale.com/r">link</a>
            <a href="https://clickbank.net/x">link</a>
            As an AI language model, this comprehensive guide will delve into
        "#;
        let report = s.analyze_page(html, "https://slop.example.com");
        assert!(report.slop_score >= 0.7);
        assert!(matches!(report.action, SlopAction::WarnBanner(_)));
    }
}
